[general]
enabled=yes
pretty=yes

; Web server settings
[http]
enabled=yes
bindaddr=0.0.0.0
bindport=8088

; ===== ARI USER (para testes via REST API) =====
[asterisk]
type=user
read_only=no
password=asterisk
password_format=plain
