[general]
dateformat=%F %T

; ===== LOG FILES =====
[logfiles]
; Format: filename => levels
console => notice,warning,error
messages => notice,warning,error
full => notice,warning,error,debug,verbose

; Para debug SIP (comentar em produção)
;sip_debug => debug,verbose
