"""
Módulo de métricas Prometheus para Media Server
"""

from metrics.prometheus_metrics import (
    # SIP Registration
    SIP_REGISTRATION_STATUS,
    SIP_REGISTRATION_SUCCESS,
    SIP_REGISTRATION_FAILURES,
    # Calls
    CALLS_INCOMING,
    CALLS_ANSWERED,
    CALLS_REJECTED,
    CALLS_ACTIVE,
    CALL_DURATION,
    # WebSocket
    WEBSOCKET_STATUS,
    WEBSOCKET_RECONNECTIONS,
    # RTP
    RTP_BYTES_RECEIVED,
    RTP_BYTES_TRANSMITTED,
    # Streaming & Barge-in
    BARGE_IN_TOTAL,
    STREAMING_LATENCY,
    VAD_DETECTION_LATENCY,
    # VAD Detalhadas
    VAD_UTTERANCE_DURATION_MS,
    VAD_EVENTS_TOTAL,
    # E2E Latency
    E2E_LATENCY_SECONDS,
    BARGE_IN_RESPONSE_PROGRESS,
    # RTP Quality
    RTP_JITTER_MS,
    RTP_PACKETS_TOTAL,
    RTP_PACKET_LOSS_RATIO,
    # RTCP / QoS
    RTCP_JITTER_MS,
    RTCP_PACKET_LOSS_TOTAL,
    RTCP_RTT_MS,
    CALL_MOS_SCORE,
    MOS_SCORE_DISTRIBUTION,
    # PLC
    PLC_EVENTS_TOTAL,
    PLC_DURATION_MS,
    # Echo Guard
    ECHO_GUARD_COOLDOWN_MS,
    ECHO_DETECTED_TOTAL,
    # Media Fork
    MEDIA_FORK_BUFFER_SIZE_BYTES,
    MEDIA_FORK_BUFFER_SIZE_MS,
    MEDIA_FORK_BUFFER_FILL_RATIO,
    MEDIA_FORK_FRAMES_RECEIVED,
    MEDIA_FORK_FRAMES_DROPPED,
    MEDIA_FORK_OVERFLOW_EVENTS,
    MEDIA_FORK_CONSUMER_LAG_MS,
    MEDIA_FORK_CONSUMER_ERRORS,
    MEDIA_FORK_AI_AGENT_AVAILABLE,
    MEDIA_FORK_FALLBACK_ACTIVE,
    # Helpers
    start_metrics_server,
    track_sip_registration,
    track_incoming_call,
    track_call_answered,
    track_call_rejected,
    track_call_ended,
    track_websocket_connected,
    track_websocket_disconnected,
    track_websocket_reconnection,
    track_rtp_received,
    track_rtp_transmitted,
    track_barge_in,
    track_streaming_latency,
    track_vad_latency,
    track_vad_event,
    track_vad_utterance_duration,
    track_e2e_latency,
    track_barge_in_progress,
    track_rtp_jitter,
    track_rtp_packet,
    track_rtp_packet_loss_ratio,
    # RTCP / QoS Helpers
    track_rtcp_jitter,
    track_rtcp_packet_loss,
    track_rtcp_rtt,
    track_mos_score,
    track_plc_event,
    track_plc_duration,
    track_echo_guard_cooldown,
    track_echo_detected,
    # Media Fork Helpers
    track_fork_buffer_size,
    track_fork_frame_received,
    track_fork_frame_dropped,
    track_fork_overflow,
    track_fork_consumer_lag,
    track_fork_consumer_error,
    track_fork_ai_agent_available,
    track_fork_fallback_active,
)

__all__ = [
    'SIP_REGISTRATION_STATUS',
    'SIP_REGISTRATION_SUCCESS',
    'SIP_REGISTRATION_FAILURES',
    'CALLS_INCOMING',
    'CALLS_ANSWERED',
    'CALLS_REJECTED',
    'CALLS_ACTIVE',
    'CALL_DURATION',
    'WEBSOCKET_STATUS',
    'WEBSOCKET_RECONNECTIONS',
    'RTP_BYTES_RECEIVED',
    'RTP_BYTES_TRANSMITTED',
    'BARGE_IN_TOTAL',
    'STREAMING_LATENCY',
    'VAD_DETECTION_LATENCY',
    'VAD_UTTERANCE_DURATION_MS',
    'VAD_EVENTS_TOTAL',
    'E2E_LATENCY_SECONDS',
    'BARGE_IN_RESPONSE_PROGRESS',
    'RTP_JITTER_MS',
    'RTP_PACKETS_TOTAL',
    'RTP_PACKET_LOSS_RATIO',
    # RTCP / QoS
    'RTCP_JITTER_MS',
    'RTCP_PACKET_LOSS_TOTAL',
    'RTCP_RTT_MS',
    'CALL_MOS_SCORE',
    'MOS_SCORE_DISTRIBUTION',
    # PLC
    'PLC_EVENTS_TOTAL',
    'PLC_DURATION_MS',
    # Echo Guard
    'ECHO_GUARD_COOLDOWN_MS',
    'ECHO_DETECTED_TOTAL',
    'start_metrics_server',
    'track_sip_registration',
    'track_incoming_call',
    'track_call_answered',
    'track_call_rejected',
    'track_call_ended',
    'track_websocket_connected',
    'track_websocket_disconnected',
    'track_websocket_reconnection',
    'track_rtp_received',
    'track_rtp_transmitted',
    'track_barge_in',
    'track_streaming_latency',
    'track_vad_latency',
    'track_vad_event',
    'track_vad_utterance_duration',
    'track_e2e_latency',
    'track_barge_in_progress',
    'track_rtp_jitter',
    'track_rtp_packet',
    'track_rtp_packet_loss_ratio',
    # RTCP / QoS Helpers
    'track_rtcp_jitter',
    'track_rtcp_packet_loss',
    'track_rtcp_rtt',
    'track_mos_score',
    'track_plc_event',
    'track_plc_duration',
    'track_echo_guard_cooldown',
    'track_echo_detected',
    # Media Fork
    'MEDIA_FORK_BUFFER_SIZE_BYTES',
    'MEDIA_FORK_BUFFER_SIZE_MS',
    'MEDIA_FORK_BUFFER_FILL_RATIO',
    'MEDIA_FORK_FRAMES_RECEIVED',
    'MEDIA_FORK_FRAMES_DROPPED',
    'MEDIA_FORK_OVERFLOW_EVENTS',
    'MEDIA_FORK_CONSUMER_LAG_MS',
    'MEDIA_FORK_CONSUMER_ERRORS',
    'MEDIA_FORK_AI_AGENT_AVAILABLE',
    'MEDIA_FORK_FALLBACK_ACTIVE',
    'track_fork_buffer_size',
    'track_fork_frame_received',
    'track_fork_frame_dropped',
    'track_fork_overflow',
    'track_fork_consumer_lag',
    'track_fork_consumer_error',
    'track_fork_ai_agent_available',
    'track_fork_fallback_active',
]
