"""
Módulo de métricas Prometheus para Media Server
"""

from metrics.prometheus_metrics import (
    # SIP Registration
    SIP_REGISTRATION_STATUS,
    SIP_REGISTRATION_SUCCESS,
    SIP_REGISTRATION_FAILURES,
    # Calls
    CALLS_INCOMING,
    CALLS_ANSWERED,
    CALLS_REJECTED,
    CALLS_ACTIVE,
    CALL_DURATION,
    # WebSocket
    WEBSOCKET_STATUS,
    WEBSOCKET_RECONNECTIONS,
    # RTP
    RTP_BYTES_RECEIVED,
    RTP_BYTES_TRANSMITTED,
    # Streaming & Barge-in
    BARGE_IN_TOTAL,
    STREAMING_LATENCY,
    VAD_DETECTION_LATENCY,
    # VAD Detalhadas
    VAD_UTTERANCE_DURATION_MS,
    VAD_EVENTS_TOTAL,
    # E2E Latency
    E2E_LATENCY_SECONDS,
    BARGE_IN_RESPONSE_PROGRESS,
    # RTP Quality
    RTP_JITTER_MS,
    RTP_PACKETS_TOTAL,
    RTP_PACKET_LOSS_RATIO,
    # Helpers
    start_metrics_server,
    track_sip_registration,
    track_incoming_call,
    track_call_answered,
    track_call_rejected,
    track_call_ended,
    track_websocket_connected,
    track_websocket_disconnected,
    track_websocket_reconnection,
    track_rtp_received,
    track_rtp_transmitted,
    track_barge_in,
    track_streaming_latency,
    track_vad_latency,
    track_vad_event,
    track_vad_utterance_duration,
    track_e2e_latency,
    track_barge_in_progress,
    track_rtp_jitter,
    track_rtp_packet,
    track_rtp_packet_loss_ratio,
)

__all__ = [
    'SIP_REGISTRATION_STATUS',
    'SIP_REGISTRATION_SUCCESS',
    'SIP_REGISTRATION_FAILURES',
    'CALLS_INCOMING',
    'CALLS_ANSWERED',
    'CALLS_REJECTED',
    'CALLS_ACTIVE',
    'CALL_DURATION',
    'WEBSOCKET_STATUS',
    'WEBSOCKET_RECONNECTIONS',
    'RTP_BYTES_RECEIVED',
    'RTP_BYTES_TRANSMITTED',
    'BARGE_IN_TOTAL',
    'STREAMING_LATENCY',
    'VAD_DETECTION_LATENCY',
    'VAD_UTTERANCE_DURATION_MS',
    'VAD_EVENTS_TOTAL',
    'E2E_LATENCY_SECONDS',
    'BARGE_IN_RESPONSE_PROGRESS',
    'RTP_JITTER_MS',
    'RTP_PACKETS_TOTAL',
    'RTP_PACKET_LOSS_RATIO',
    'start_metrics_server',
    'track_sip_registration',
    'track_incoming_call',
    'track_call_answered',
    'track_call_rejected',
    'track_call_ended',
    'track_websocket_connected',
    'track_websocket_disconnected',
    'track_websocket_reconnection',
    'track_rtp_received',
    'track_rtp_transmitted',
    'track_barge_in',
    'track_streaming_latency',
    'track_vad_latency',
    'track_vad_event',
    'track_vad_utterance_duration',
    'track_e2e_latency',
    'track_barge_in_progress',
    'track_rtp_jitter',
    'track_rtp_packet',
    'track_rtp_packet_loss_ratio',
]
